name: Scrape CPCB Data

on:
  workflow_dispatch: # Allows you to run this workflow manually from the Actions tab
  schedule:
    # Runs at 06:00 UTC (11:30 AM IST) every day
    - cron: '0 6 * * *'
    # Runs at 18:00 UTC (11:30 PM IST) every day
    - cron: '0 18 * * *'

jobs:
  build-and-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas requests

      - name: Run the scraper
        run: python cpcb_scraper.py

      - name: Commit data files
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add *.csv
          git diff --staged --quiet || git commit -m "Update water quality data"
          git push