name: Scrape and Upload to Drive

on:
  workflow_dispatch: # Allows manual runs
  schedule:
    # Runs at the beginning of every hour
    - cron: '0 * * * *'

jobs:
  build-and-upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Python dependencies
        run: pip install pandas requests

      - name: Run Python scraper
        run: python cpcb_scraper.py

      - name: Upload file to Google Drive
        uses: adityak74/google-drive-upload-git-action@v1.3
        with:
          credentials: ${{ secrets.GDRIVE_CREDENTIALS }}
          folder_id: 1qSb7_elWCqp8dPfO5rj3NJk5HVYxTXBY
          filename: "*.csv"
